# Generated by Django 4.2.16 on 2025-02-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='image_url',
            field=models.URLField(default='https://via.placeholder.com/600x400'),
        ),
    ]
